project:
  type: website
  output-dir: docs

website:
  title: "Jess Diaz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pubs.qmd
        text: Publications
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme: styles.scss
    mainfont: Rubik
    toc: true
    page-layout: full
